version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - riftterdb
  riftterdb:
    build: ./postgresDb/
    ports: 
      - "5432:5432"
  redisdb:
    image: redis
    ports:
      - "6379:6379"