version: "3.9"
services:
  test_riftterdb:
    image: library/postgres
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_riftterdb
    container_name: 'postgres-for-test'
    ports:
      - '5432:5432'
    tmpfs: /var/lib/postgresql/data
  redisdb:
    image: redis
    container_name: redis-for-test
    ports:
      - "6379:6379"